# syntax = docker/dockerfile:1.2

FROM rust:1.63.0 as builder
WORKDIR /app
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
COPY src src
# This works with the dummy project generated by `cargo new app --bin`
#RUN --mount=type=cache,sharing=locked,target=/app/target \
#    cargo build --release
RUN cargo build --release

FROM gcr.io/distroless/cc as runtime
WORKDIR /app
COPY --from=builder /app/target/release/k8s-controller /usr/bin/k8s-controller